# Generated by Django 5.2.17 on 2026-10-03 14:18

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('workorders', '0003_workorder_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoverageAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='Contract / warranty number, unique per organization.', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('WARRANTY', 'Warranty'), ('AMC', 'Annual maintenance contract'), ('SERVICE_CONTRACT', 'Service contract')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('terms', models.TextField(blank=True, help_text='Coverage terms.')),
                ('exclusion_notes', models.TextField(blank=True, help_text='Free-text exclusions (structured ones are rows).')),
                ('sla_terms', models.CharField(blank=True, help_text='Provider response terms (information only; M11 owns SLA behaviour).', max_length=300)),
                ('renewal_alert_days', models.PositiveSmallIntegerField(default=30)),
                ('renewal_alerted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivation_reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('renewed_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal', to='contracts.coverageagreement')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_agreements', to='sites.site')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='contracts.serviceprovider')),
            ],
            options={
                'ordering': ['end_date', 'reference'],
            },
        ),
        migrations.CreateModel(
            name='CoverageCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.CharField(max_length=20)),
                ('reference_date', models.DateField()),
                ('eligible', models.BooleanField()),
                ('reason', models.CharField(max_length=500)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='contracts.coverageagreement')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.asset')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_checks', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'work_order'], name='contracts_c_organiz_bf8c82_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoverageExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_type', models.CharField(max_length=20)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='contracts.coverageagreement')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agreement', 'work_type'), name='uniq_exclusion_per_type')],
            },
        ),
        migrations.CreateModel(
            name='CoveredAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_assets', to='contracts.coverageagreement')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_links', to='assets.asset')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'asset'], name='contracts_c_organiz_a34982_idx')],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'asset'), name='uniq_asset_per_agreement')],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceprovider',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='uniq_provider_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='coverageagreement',
            index=models.Index(fields=['organization', 'site'], name='contracts_c_organiz_172ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='coverageagreement',
            index=models.Index(fields=['organization', 'is_active', 'end_date'], name='contracts_c_organiz_0e4cdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='coverageagreement',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('reference'), models.F('organization'), name='uniq_agreement_ref_per_org'),
        ),
        migrations.AddConstraint(
            model_name='coverageagreement',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='agreement_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='coverageagreement',
            constraint=models.CheckConstraint(condition=models.Q(('renewal_alert_days__lte', 365)), name='agreement_alert_days'),
        ),
    ]
