# Generated by Django 5.2.17 on 2026-10-04 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('sla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverageagreement',
            name='sla_profile',
            field=models.ForeignKey(blank=True, help_text='Internal SLA profile (M11) applied to work covered by this agreement; it overrides the site / organization profile for the covered assets while the agreement is in force.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sla.slaprofile'),
        ),
    ]
