# Generated by Django 5.2.17 on 2026-10-03 13:15

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
        ('rbac', '0002_membership_role_site_scope'),
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('workorders', '0003_workorder_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('applies_to', models.CharField(choices=[('REQUEST', 'Service requests / incidents (M05)'), ('WORK_ORDER', 'Work orders (M06)')], max_length=12)),
                ('work_type', models.CharField(blank=True, help_text='Work-order profiles: only this work type', max_length=20)),
                ('pause_states', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('site', models.ForeignKey(blank=True, help_text='Blank = the whole organization; a site profile wins over it', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_kind', models.CharField(choices=[('RESPONSE', 'Response'), ('RESOLUTION', 'Resolution')], max_length=10)),
                ('trigger', models.CharField(choices=[('WARNING', 'Warning threshold reached'), ('BREACH', 'Target breached'), ('ESCALATION', 'Still unmet after the breach')], max_length=10)),
                ('after_minutes', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('notify_assignee', models.BooleanField(default=False)),
                ('notify_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rbac.role')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sla.slaprofile')),
            ],
            options={
                'ordering': ['profile__name', 'target_kind', 'trigger', 'after_minutes'],
            },
        ),
        migrations.CreateModel(
            name='SLATarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(max_length=10)),
                ('response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
                ('warning_percent', models.PositiveSmallIntegerField(default=80)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='sla.slaprofile')),
            ],
            options={
                'ordering': ['profile__name', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='SLATracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(max_length=10)),
                ('response_minutes', models.PositiveIntegerField()),
                ('resolution_minutes', models.PositiveIntegerField()),
                ('warning_percent', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField()),
                ('response_due_at', models.DateTimeField()),
                ('resolution_due_at', models.DateTimeField()),
                ('response_met_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_met_at', models.DateTimeField(blank=True, null=True)),
                ('response_state', models.CharField(choices=[('PENDING', 'Pending'), ('MET', 'Met'), ('MET_LATE', 'Met late'), ('BREACHED', 'Breached'), ('NOT_APPLICABLE', 'Not applicable')], default='PENDING', max_length=14)),
                ('resolution_state', models.CharField(choices=[('PENDING', 'Pending'), ('MET', 'Met'), ('MET_LATE', 'Met late'), ('BREACHED', 'Breached'), ('NOT_APPLICABLE', 'Not applicable')], default='PENDING', max_length=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=10)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_seconds', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trackings', to='sla.slaprofile')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_trackings', to='incidents.servicerequest')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_trackings', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=20)),
                ('target_kind', models.CharField(blank=True, max_length=10)),
                ('at', models.DateTimeField()),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(blank=True, max_length=80)),
                ('notified', models.PositiveSmallIntegerField(default=0)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sla.escalationrule')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sla.slatracking')),
            ],
            options={
                'ordering': ['at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLABreach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_kind', models.CharField(choices=[('RESPONSE', 'Response'), ('RESOLUTION', 'Resolution')], max_length=10)),
                ('priority', models.CharField(max_length=10)),
                ('severity', models.CharField(default='MAJOR', max_length=10)),
                ('breached_at', models.DateTimeField(help_text='The due instant that was missed')),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=14)),
                ('escalation_level', models.PositiveSmallIntegerField(default=0)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.CharField(blank=True, max_length=60)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sla.slaprofile')),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breaches', to='sla.slatracking')),
            ],
            options={
                'ordering': ['-breached_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='slaprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='uniq_sla_profile_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='slaprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('site__isnull', True)), fields=('organization', 'applies_to', 'work_type'), name='uniq_active_sla_profile_org_scope'),
        ),
        migrations.AddConstraint(
            model_name='slaprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('site__isnull', False)), fields=('organization', 'applies_to', 'work_type', 'site'), name='uniq_active_sla_profile_site_scope'),
        ),
        migrations.AddConstraint(
            model_name='escalationrule',
            constraint=models.UniqueConstraint(fields=('profile', 'target_kind', 'trigger', 'after_minutes'), name='uniq_escalation_rule_step'),
        ),
        migrations.AddConstraint(
            model_name='escalationrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('after_minutes__gte', 1), ('trigger', 'ESCALATION')), models.Q(models.Q(('trigger', 'ESCALATION'), _negated=True), ('after_minutes', 0)), _connector='OR'), name='escalation_after_minutes'),
        ),
        migrations.AddConstraint(
            model_name='escalationrule',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 3)), name='escalation_level_range'),
        ),
        migrations.AddConstraint(
            model_name='escalationrule',
            constraint=models.CheckConstraint(condition=models.Q(('notify_role__isnull', False), ('notify_assignee', True), _connector='OR'), name='escalation_has_recipient'),
        ),
        migrations.AddConstraint(
            model_name='slatarget',
            constraint=models.UniqueConstraint(fields=('profile', 'priority'), name='uniq_sla_target_per_priority'),
        ),
        migrations.AddConstraint(
            model_name='slatarget',
            constraint=models.CheckConstraint(condition=models.Q(('response_minutes__gte', 1)), name='sla_response_minutes_pos'),
        ),
        migrations.AddConstraint(
            model_name='slatarget',
            constraint=models.CheckConstraint(condition=models.Q(('resolution_minutes__gte', models.F('response_minutes'))), name='sla_resolution_gte_response'),
        ),
        migrations.AddConstraint(
            model_name='slatarget',
            constraint=models.CheckConstraint(condition=models.Q(('warning_percent__gte', 1), ('warning_percent__lte', 99)), name='sla_warning_percent_range'),
        ),
        migrations.AddIndex(
            model_name='slatracking',
            index=models.Index(fields=['organization', 'status'], name='sla_slatrac_organiz_7c2a87_idx'),
        ),
        migrations.AddIndex(
            model_name='slatracking',
            index=models.Index(fields=['organization', 'site'], name='sla_slatrac_organiz_ddba95_idx'),
        ),
        migrations.AddIndex(
            model_name='slatracking',
            index=models.Index(fields=['organization', 'priority'], name='sla_slatrac_organiz_967b3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='slatracking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('request__isnull', False), ('work_order__isnull', True)), models.Q(('request__isnull', True), ('work_order__isnull', False)), _connector='OR'), name='sla_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='slatracking',
            constraint=models.UniqueConstraint(condition=models.Q(('request__isnull', False)), fields=('request',), name='uniq_sla_tracking_per_request'),
        ),
        migrations.AddConstraint(
            model_name='slatracking',
            constraint=models.UniqueConstraint(condition=models.Q(('work_order__isnull', False)), fields=('work_order',), name='uniq_sla_tracking_per_work_order'),
        ),
        migrations.AddConstraint(
            model_name='slatracking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paused_at__isnull', False), ('status', 'PAUSED')), models.Q(models.Q(('status', 'PAUSED'), _negated=True), ('paused_at__isnull', True)), _connector='OR'), name='sla_paused_has_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='slaevent',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('tracking', 'dedupe_key'), name='uniq_sla_event_dedupe'),
        ),
        migrations.AddIndex(
            model_name='slabreach',
            index=models.Index(fields=['organization', 'status'], name='sla_slabrea_organiz_9cd1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='slabreach',
            index=models.Index(fields=['organization', 'site'], name='sla_slabrea_organiz_a6ffb2_idx'),
        ),
        migrations.AddConstraint(
            model_name='slabreach',
            constraint=models.UniqueConstraint(fields=('tracking', 'target_kind'), name='uniq_sla_breach_per_target'),
        ),
    ]
