# Generated by Django 5.2.17 on 2026-10-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('sla', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='slaprofile',
            name='uniq_active_sla_profile_org_scope',
        ),
        migrations.RemoveConstraint(
            model_name='slaprofile',
            name='uniq_active_sla_profile_site_scope',
        ),
        migrations.AddField(
            model_name='slaprofile',
            name='coverage_only',
            field=models.BooleanField(default=False, help_text='Used only through a warranty / AMC / contract that names it (M10); never resolved by scope.'),
        ),
        migrations.AddConstraint(
            model_name='slaprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('coverage_only', False), ('is_active', True), ('site__isnull', True)), fields=('organization', 'applies_to', 'work_type'), name='uniq_active_sla_profile_org_scope'),
        ),
        migrations.AddConstraint(
            model_name='slaprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('coverage_only', False), ('is_active', True), ('site__isnull', False)), fields=('organization', 'applies_to', 'work_type', 'site'), name='uniq_active_sla_profile_site_scope'),
        ),
    ]
