# Generated by Django 5.2.17 on 2026-10-03 18:07

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=20)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('payload', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-period_to', 'kind'],
                'indexes': [models.Index(fields=['organization', 'kind', '-period_to'], name='dashboards__organiz_c3278b_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'kind', 'period_to'), name='uniq_report_snapshot_per_org_kind_day')],
            },
        ),
    ]
