# Generated by Django 5.2.17 on 2026-10-03 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(blank=True, help_text='Client company / department, for staff.', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='portal_account', to='tenancy.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['membership__user__email'],
            },
        ),
        migrations.CreateModel(
            name='PortalAssetGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='portal.portalaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portal_grants', to='assets.asset')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='portalaccount',
            index=models.Index(fields=['organization', 'is_active'], name='portal_port_organiz_666400_idx'),
        ),
        migrations.AddIndex(
            model_name='portalassetgrant',
            index=models.Index(fields=['organization', 'asset'], name='portal_port_organiz_aaaf52_idx'),
        ),
        migrations.AddConstraint(
            model_name='portalassetgrant',
            constraint=models.UniqueConstraint(fields=('account', 'asset'), name='uniq_portal_grant'),
        ),
    ]
