# Generated by Django 5.2.17 on 2026-10-03 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('kind', models.CharField(choices=[('INCIDENT', 'Incident / breakdown'), ('SERVICE_REQUEST', 'Service request')], default='INCIDENT', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('service_impact', models.CharField(choices=[('NONE', 'No service impact'), ('DEGRADED', 'Degraded service'), ('PARTIAL_OUTAGE', 'Partial outage'), ('FULL_OUTAGE', 'Full outage')], default='NONE', max_length=20)),
                ('impact_notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('TRIAGED', 'Triaged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WORK_ORDER_CREATED', 'Work Order Created'), ('IN_SERVICE', 'In Service'), ('RESOLVED', 'Resolved'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=20)),
                ('occurred_at', models.DateTimeField(help_text='When the failure / need was noticed.')),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='assets.asset')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_requests', to='tenancy.membership')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_source', models.CharField(blank=True, help_text='manual | work_order', max_length=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtimes', to='assets.asset')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='downtime', to='incidents.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='manual', help_text='manual | work_order', max_length=20)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='incidents.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'status'], name='incidents_s_organiz_008435_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'site'], name='incidents_s_organiz_4eeedb_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'asset'], name='incidents_s_organiz_f04406_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['organization', 'severity'], name='incidents_s_organiz_435feb_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicerequest',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_request_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='downtime',
            index=models.Index(fields=['organization', 'asset'], name='incidents_d_organiz_e3e6c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='downtime',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='downtime_end_after_start'),
        ),
    ]
