# Generated by Django 5.2.17 on 2026-10-03 09:11

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.UUIDField(db_index=True, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=10)),
                ('work_type', models.CharField(blank=True, help_text='Blank = any work type', max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Must be completed before matching work can be completed / closed')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('prompt', models.CharField(max_length=300)),
                ('guidance', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMERIC', 'Number'), ('BOOLEAN', 'Pass / fail'), ('SELECTION', 'Selection')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('exception_options', models.JSONField(blank=True, default=list)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('evidence_required', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='checklists.checklisttemplate')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='assets.asset')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='sites.site')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='checklists.checklisttemplate')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='checklists.checklistitem')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='sites.site')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='workorders.workorder')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='checklists.inspection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('value_bool', models.BooleanField(null=True)),
                ('is_exception', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField()),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.inspection')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklistitem')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['organization', 'status'], name='checklists__organiz_52ff07_idx'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'key', 'version'), name='uniq_checklist_version'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('organization', 'key'), name='uniq_active_checklist_per_key'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('template', 'position'), name='uniq_checklist_item_position'),
        ),
        migrations.AddConstraint(
            model_name='checklistitem',
            constraint=models.CheckConstraint(condition=models.Q(('min_value__isnull', True), ('max_value__isnull', True), ('max_value__gte', models.F('min_value')), _connector='OR'), name='checklist_item_range'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['organization', 'status'], name='checklists__organiz_38532e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['organization', 'site'], name='checklists__organiz_7ca398_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['organization', 'work_order'], name='checklists__organiz_0c9d13_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspection',
            constraint=models.UniqueConstraint(condition=models.Q(('work_order__isnull', False)), fields=('work_order', 'template'), name='uniq_inspection_per_work_order_template'),
        ),
        migrations.AddConstraint(
            model_name='inspection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', False), _connector='OR'), name='inspection_completed_has_timestamp'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['organization', 'status'], name='checklists__organiz_379553_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['organization', 'site'], name='checklists__organiz_59f5db_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionresponse',
            index=models.Index(fields=['inspection'], name='checklists__inspect_9ffdac_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionresponse',
            constraint=models.UniqueConstraint(fields=('inspection', 'item'), name='uniq_response_per_item'),
        ),
    ]
