#!/usr/bin/env python
"""Generates ``docs/ER_DIAGRAM.md`` (Mermaid ER diagram + table inventory) from the live Django models.

    PYTHONPATH=src DJANGO_SETTINGS_MODULE=config.settings.test DATABASE_URL=... python scripts/generate_erd.py

Reads model metadata only; opens no database connection and changes nothing but the output file."""
import os
import pathlib
import sys

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.test")
os.environ.setdefault("DATABASE_URL", "postgres://u:p@localhost:5432/x")
os.environ.setdefault("DJANGO_SECRET_KEY", "erd-generation-only")
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))

import django  # noqa: E402

django.setup()
from django.apps import apps  # noqa: E402

from apps.core.models import TenantOwnedModel  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "docs" / "ER_DIAGRAM.md"
MODULE_OF = {"sites": "M01", "assets": "M02/M03", "maintenance": "M04", "incidents": "M05", "workorders": "M06",
             "workspace": "M07", "checklists": "M08", "inventory": "M09", "contracts": "M10", "sla": "M11",
             "identification": "M12", "portal": "M13", "dashboards": "M14", "audit": "M15"}


def main() -> None:
    models = sorted((m for m in apps.get_models() if m._meta.app_label not in {"admin", "auth", "contenttypes",
                                                                                   "sessions", "axes", "token_blacklist"}),
                    key=lambda m: (m._meta.app_label, m.__name__))
    names = {m: f"{m._meta.app_label}_{m.__name__}" for m in models}
    lines = ["# ER diagram (generated)", "",
             "Generated by `scripts/generate_erd.py` from the Django models; do not edit by hand. Every tenant-owned table",
             "carries an `organization_id` foreign key (see `docs/ARCHITECTURE.md`); the inventory below marks them.", "",
             "```mermaid", "erDiagram"]
    for m in models:
        lines.append(f"  {names[m]} {{")
        for f in m._meta.concrete_fields:
            kind = f.get_internal_type()
            key = " PK" if f.primary_key else (" FK" if f.is_relation else "")
            lines.append(f"    {kind}{'_' if False else ''} {f.name}{key}")
        lines.append("  }")
    seen = set()
    for m in models:
        for f in m._meta.concrete_fields:
            if f.is_relation and f.related_model in names and f.name != "organization":
                tgt = names[f.related_model]
                card = "|o" if f.null else "||"
                edge = (names[m], tgt, f.name)
                if edge not in seen:
                    seen.add(edge)
                    lines.append(f"  {tgt} {card}--o{{ {names[m]} : \"{f.name}\"")
    lines += ["```", "", "## Table inventory", "", "| Module | Model | Table | Tenant-owned (organization FK) | Fields | Relations |",
              "|---|---|---|---|---|---|"]
    for m in models:
        tenant = "yes" if issubclass(m, TenantOwnedModel) else ("platform-level" if m.__name__ in
                                                               {"Organization", "User", "Permission"} else "indirect/other")
        rel = sum(1 for f in m._meta.concrete_fields if f.is_relation)
        lines.append(f"| {MODULE_OF.get(m._meta.app_label, 'foundation')} | {m.__name__} | `{m._meta.db_table}` | {tenant} | "
                     f"{len(m._meta.concrete_fields)} | {rel} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(models)} models)")


if __name__ == "__main__":
    main()
