# Generated by Django 5.2.17 on 2026-10-03 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('incidents', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('QR', 'QR code'), ('BARCODE', 'Barcode (Code 128)')], max_length=10)),
                ('token', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=300)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='assets.asset')),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='identification.assetidentifier')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='incidents.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assetidentifier',
            index=models.Index(fields=['organization', 'asset'], name='identificat_organiz_8e49e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetidentifier',
            constraint=models.UniqueConstraint(fields=('token',), name='uniq_identifier_token'),
        ),
        migrations.AddConstraint(
            model_name='assetidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('asset', 'kind'), name='uniq_active_identifier_per_asset_kind'),
        ),
        migrations.AddConstraint(
            model_name='assetidentifier',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), ('revoked_at__isnull', True)), models.Q(('is_active', False), ('revoked_at__isnull', False)), _connector='OR'), name='identifier_revocation_consistent'),
        ),
        migrations.AddIndex(
            model_name='scanevent',
            index=models.Index(fields=['organization', 'asset'], name='identificat_organiz_69030a_idx'),
        ),
    ]
