# Generated by Django 5.2.17 on 2026-10-03 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='part_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_rows', to='inventory.workorderpart'),
        ),
    ]
