# Generated by Django 5.2.17 on 2026-10-03 10:28

from django.conf import settings
from django.db import migrations, models


def backfill_request_source(apps, schema_editor):
    """Orders created from a service request get source_type / source_id (additive; nothing else changes)."""
    WorkOrder = apps.get_model("workorders", "WorkOrder")
    for wo in WorkOrder._base_manager.filter(source_request__isnull=False).only("id", "source_request_id").iterator():
        WorkOrder._base_manager.filter(pk=wo.pk).update(source_type="SERVICE_REQUEST", source_id=wo.source_request_id)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('incidents', '0001_initial'),
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('workorders', '0002_workordermaterial_part_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='source_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='source_type',
            field=models.CharField(blank=True, choices=[('SERVICE_REQUEST', 'Service request'), ('PREVENTIVE_MAINTENANCE', 'Preventive maintenance')], max_length=30),
        ),
        migrations.RunPython(backfill_request_source, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', ''), ('source_id__isnull', True)), models.Q(models.Q(('source_type', ''), _negated=True), ('source_id__isnull', False)), _connector='OR'), name='work_order_source_pair'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type', 'PREVENTIVE_MAINTENANCE')), fields=('source_id',), name='uniq_work_order_per_pm_source'),
        ),
    ]
