# Generated by Django 5.2.17 on 2026-10-03 05:22

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
                ('status_reason', models.CharField(blank=True, max_length=300)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OperatingCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('working_days', models.JSONField(default=list, help_text='ISO weekday numbers, 1=Monday ... 7=Sunday')),
                ('is_24x7', models.BooleanField(default=False)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calendars', to='sites.site')),
            ],
            options={
                'ordering': ['site__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('role_title', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('escalation_order', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='sites.site')),
            ],
            options={
                'ordering': ['site__code', 'escalation_order'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_type', models.CharField(choices=[('BUILDING', 'Building'), ('ZONE', 'Zone / area'), ('SERVICE_AREA', 'Service area')], default='ZONE', max_length=14)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
                ('status_reason', models.CharField(blank=True, max_length=300)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sites.zone')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='sites.operatingcalendar')),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('calendar', 'date'), name='uniq_holiday_per_calendar_date')],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'status'], name='sites_site_organiz_e4955b_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='uniq_site_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='operatingcalendar',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('site'), name='uniq_calendar_name_per_site'),
        ),
        migrations.AddConstraint(
            model_name='operatingcalendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('site',), name='uniq_default_calendar_per_site'),
        ),
        migrations.AddConstraint(
            model_name='sitecontact',
            constraint=models.UniqueConstraint(fields=('site', 'escalation_order'), name='uniq_contact_order_per_site'),
        ),
        migrations.AddConstraint(
            model_name='sitecontact',
            constraint=models.CheckConstraint(condition=models.Q(('escalation_order__gte', 1)), name='contact_order_gte_1'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['organization', 'site'], name='sites_zone_organiz_273191_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('site'), condition=models.Q(('parent__isnull', True)), name='uniq_zone_name_root'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('site'), models.F('parent'), condition=models.Q(('parent__isnull', False)), name='uniq_zone_name_under_parent'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('site'), condition=models.Q(('code', ''), _negated=True), name='uniq_zone_code_per_site'),
        ),
    ]
