# Generated by Django 5.2.17 on 2026-10-03 09:56

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_number', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('min_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='sites.site')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('min_level', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_level', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.part')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['warehouse__code', 'part__part_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('RESERVED', 'Reserved'), ('ISSUED', 'Issued'), ('CONSUMED', 'Consumed'), ('RETURNED', 'Returned'), ('RECONCILED', 'Reconciled'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=12)),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_issued', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_consumed', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_returned', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_lines', to='inventory.part')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_lines', to='inventory.warehouse')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_lines', to='workorders.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue to work order'), ('RETURN', 'Return from work order'), ('TRANSFER_OUT', 'Transfer out'), ('TRANSFER_IN', 'Transfer in'), ('ADJUSTMENT', 'Adjustment'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release reservation')], db_index=True, max_length=14)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('on_hand_delta', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reserved_delta', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('on_hand_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reserved_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('transfer_ref', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockbalance')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.part')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='workorders.workorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
                ('part_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.workorderpart')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RELEASED', 'Released'), ('FULFILLED', 'Fulfilled')], db_index=True, default='ACTIVE', max_length=10)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_reservations', to='workorders.workorder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse')),
                ('part_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='inventory.workorderpart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('part_number'), models.F('organization'), name='uniq_part_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__isnull', True), ('min_stock__gte', 0), _connector='OR'), name='part_min_stock_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.CheckConstraint(condition=models.Q(('min_stock__isnull', True), ('max_stock__isnull', True), ('max_stock__gte', models.F('min_stock')), _connector='OR'), name='part_max_gte_min'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['organization', 'site'], name='inventory_w_organiz_75fc50_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('organization'), name='uniq_warehouse_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['organization', 'part'], name='inventory_s_organiz_01441c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'part'), name='uniq_balance_per_warehouse_part'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand__gte', 0)), name='balance_on_hand_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__gte', 0)), name='balance_reserved_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('reserved__lte', models.F('on_hand'))), name='balance_reserved_lte_on_hand'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('min_level__isnull', True), ('max_level__isnull', True), ('max_level__gte', models.F('min_level')), _connector='OR'), name='balance_max_gte_min'),
        ),
        migrations.AddIndex(
            model_name='workorderpart',
            index=models.Index(fields=['organization', 'work_order'], name='inventory_w_organiz_f13ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderpart',
            index=models.Index(fields=['organization', 'status'], name='inventory_w_organiz_6b1ab6_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.UniqueConstraint(fields=('work_order', 'part'), name='uniq_part_line_per_work_order'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_requested__gt', 0)), name='part_line_requested_pos'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_consumed__gte', 0), ('quantity_issued__gte', 0), ('quantity_returned__gte', 0)), name='part_line_quantities_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='workorderpart',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_consumed__lte', django.db.models.expressions.CombinedExpression(models.F('quantity_issued'), '-', models.F('quantity_returned')))), name='part_line_consumed_returned_lte_issued'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'warehouse', 'part', '-created_at'], name='inventory_s_organiz_682b66_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'work_order'], name='inventory_s_organiz_8c58b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='movement_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('on_hand_delta', 0), _negated=True), models.Q(('reserved_delta', 0), _negated=True), _connector='OR'), name='movement_changes_balance'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('on_hand_after__gte', 0), ('reserved_after__gte', 0)), name='movement_after_nonneg'),
        ),
        migrations.AddIndex(
            model_name='partreservation',
            index=models.Index(fields=['organization', 'status'], name='inventory_p_organiz_f21e43_idx'),
        ),
        migrations.AddIndex(
            model_name='partreservation',
            index=models.Index(fields=['organization', 'warehouse', 'part'], name='inventory_p_organiz_e64aa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='partreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='reservation_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='partreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), _negated=True), ('quantity__gt', 0), _connector='OR'), name='reservation_active_has_qty'),
        ),
    ]
