# Generated by Django 5.2.17 on 2026-10-03 05:43

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'verbose_name_plural': 'asset categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_tag', models.CharField(help_text='Human-readable identifier, unique per organization.', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('commission_date', models.DateField(blank=True, null=True)),
                ('warranty_ref', models.CharField(blank=True, help_text='Free-text reference; coverage logic belongs to M10 (later).', max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out Of Service'), ('RETIRED', 'Retired'), ('DISPOSED', 'Disposed')], db_index=True, default='ACTIVE', max_length=20)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_assets', to='tenancy.membership')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='sites.zone')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
            ],
            options={
                'ordering': ['asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('ASSEMBLY', 'Assembly'), ('COMPONENT', 'Component'), ('REPLACEABLE_PART', 'Replaceable part')], default='COMPONENT', max_length=20)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('part_number', models.CharField(blank=True, help_text='Bridge to M09 inventory parts (later).', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parent_link', to='assets.asset')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_links', to='assets.asset')),
            ],
            options={
                'ordering': ['parent__asset_tag', 'child__asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('doc_type', models.CharField(choices=[('MANUAL', 'Manual'), ('DATASHEET', 'Datasheet / specification'), ('CERTIFICATE', 'Certificate'), ('COMMISSIONING', 'Commissioning record'), ('PHOTO', 'Photograph'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='assets.asset')),
                ('attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='files.attachment')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetLocationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_history', to='assets.asset')),
                ('from_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site')),
                ('from_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.zone')),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('to_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site')),
                ('to_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.zone')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Run hours, Odometer, Cycle count', max_length=80)),
                ('unit', models.CharField(help_text='e.g. h, km, cycles', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='assets.asset')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetMeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=16)),
                ('read_at', models.DateTimeField()),
                ('source', models.CharField(default='manual', max_length=40)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='assets.assetmeter')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-read_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='manual', help_text='manual, or the module that caused it', max_length=40)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='assets.asset')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='uniq_asset_category_per_org'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'status'], name='assets_asse_organiz_ad90f0_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'site'], name='assets_asse_organiz_8f52ee_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'category'], name='assets_asse_organiz_26a143_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['organization', 'serial_number'], name='assets_asse_organiz_a1b249_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('asset_tag'), models.F('organization'), name='uniq_asset_tag_per_org'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('manufacturer'), django.db.models.functions.text.Lower('serial_number'), models.F('organization'), condition=models.Q(('serial_number', ''), _negated=True), name='uniq_asset_serial_per_maker_org'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_date__isnull', True), ('commission_date__isnull', True), ('commission_date__gte', models.F('purchase_date')), _connector='OR'), name='asset_commission_after_purchase'),
        ),
        migrations.AddIndex(
            model_name='assetcomponent',
            index=models.Index(fields=['organization', 'parent'], name='assets_asse_organiz_f4dd7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='component_not_self'),
        ),
        migrations.AddConstraint(
            model_name='assetcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='component_quantity_gte_1'),
        ),
        migrations.AddIndex(
            model_name='assetdocument',
            index=models.Index(fields=['asset', '-created_at'], name='assets_asse_asset_i_044ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='assetlocationhistory',
            index=models.Index(fields=['asset', '-created_at'], name='assets_asse_asset_i_f80fb6_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetmeter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('asset'), name='uniq_meter_name_per_asset'),
        ),
        migrations.AddIndex(
            model_name='assetmeterreading',
            index=models.Index(fields=['meter', '-read_at'], name='assets_asse_meter_i_0425ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetmeterreading',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='meter_reading_gte_0'),
        ),
        migrations.AddIndex(
            model_name='assetstatushistory',
            index=models.Index(fields=['asset', '-created_at'], name='assets_asse_asset_i_cfd73c_idx'),
        ),
    ]
