# Generated by Django 5.2.17 on 2026-10-04 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text="Values of the category's custom attributes (key -> text)."),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='attribute_definitions',
            field=models.JSONField(blank=True, default=list, help_text='Custom attributes assets of this category carry (see assets.attributes).'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='removed_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
