# Generated by Django 5.2.17 on 2026-10-03 10:31

import datetime
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('sites', '0001_initial'),
        ('tenancy', '0001_initial'),
        ('workorders', '0003_workorder_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(default='MEDIUM', max_length=10)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('checklist_key', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='assets.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='sites.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('TIME', 'Time-based'), ('METER', 'Meter-based')], max_length=6)),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Day(s)'), ('WEEKLY', 'Week(s)'), ('MONTHLY', 'Month(s)'), ('QUARTERLY', 'Quarter(s)'), ('YEARLY', 'Year(s)')], max_length=10)),
                ('interval_count', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('interval_value', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('start_value', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('lead_days', models.PositiveSmallIntegerField(default=0, help_text='Generate the work order this many days early')),
                ('window_start_time', models.TimeField(default=datetime.time(8, 0))),
                ('window_hours', models.PositiveSmallIntegerField(default=8, help_text='Length of the maintenance window')),
                ('reminder_days', models.PositiveSmallIntegerField(default=0, help_text='Remind planners this many days before due')),
                ('is_active', models.BooleanField(default=True)),
                ('next_sequence', models.PositiveIntegerField(default=0)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('next_due_value', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('last_reminded_sequence', models.IntegerField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedules', to='assets.assetmeter')),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='maintenance.maintenanceplan')),
            ],
            options={
                'ordering': ['plan__name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_value', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('trigger', models.CharField(default='scheduler', max_length=10)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('work_order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_cycle', to='workorders.workorder')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='maintenance.maintenanceschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['organization', 'site'], name='maintenance_organiz_7c18ea_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['organization', 'is_active'], name='maintenance_organiz_9b2667_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceplan',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('asset'), name='uniq_plan_name_per_asset'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['organization', 'is_active', 'next_due_date'], name='maintenance_organiz_e291ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('frequency__in', ['DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY']), ('interval_count__gte', 1), ('interval_value__isnull', True), ('meter__isnull', True), ('start_date__isnull', False), ('trigger_type', 'TIME')), models.Q(('frequency', ''), ('interval_count__isnull', True), ('interval_value__gt', 0), ('meter__isnull', False), ('start_date__isnull', True), ('trigger_type', 'METER')), _connector='OR'), name='schedule_trigger_fields'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('lead_days__lte', 60), ('reminder_days__lte', 60), ('window_hours__gte', 1), ('window_hours__lte', 72)), name='schedule_window_ranges'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_type', 'TIME')), fields=('plan', 'frequency', 'interval_count'), name='uniq_time_schedule_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='maintenanceschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger_type', 'METER')), fields=('plan', 'meter', 'interval_value'), name='uniq_meter_schedule_per_plan'),
        ),
        migrations.AddIndex(
            model_name='maintenancecycle',
            index=models.Index(fields=['organization', 'schedule'], name='maintenance_organiz_f51926_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancecycle',
            constraint=models.UniqueConstraint(fields=('schedule', 'sequence'), name='uniq_cycle_per_schedule_sequence'),
        ),
    ]
