# Generated by Django 5.2.17 on 2026-10-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceschedule",
            name="sequence_offset",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
